server:
  port: 10020
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  application:
    name: blog-server
  datasource:
    dynamic:
      datasource:
        blog:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/mytestdb?serverTimezone=Asia/Shanghai
          username: root
          password:
        user:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Shanghai
          username: root
          password:
      primary: blog

# http://localhost:8080/oauth/authorize?client_id=user&response_type=code

security:
  oauth2:
    client:

# .properties文件client-id错误
      client-id: blog
      client-secret: secret
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      user-info-uri:
      jwt:
        key-uri: http://localhost:8080/oauth/token_key
#将IP注册到Eureka Server
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://EUREKA-01:9010/eureka/

