server:
  port: 10000
spring:
  application:
    name: APIS-GATEWAY

# http://localhost:8080/oauth/authorize?client_id=apis-gateway&response_type=code
security:
  oauth2:
    client:
      # .propertiesÎÄ¼þclient-id´íÎó
      client-id: apis-gateway
      client-secret: secret
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      user-info-uri:
      jwt:
        key-uri: http://localhost:8080/oauth/token_key

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://EUREKA-01:9010/eureka/, http://EUREKA-02:9020/eureka/
zuul:
  routes:
    USER-SERVER:
      path: /user/**
      serviceId: USER-SERVER
    ADMIN-SERVER:
      path: /admin/**
      serviceId: ADMIN-SERVER
    BLOG-SERVER:
      path: /blog/**
      serviceId: BLOG-SERVER